### PR TITLE
Add Ability to Use Multiple Spa Apps

### PR DESCRIPTION
**Pull request by JohnCampionJr**
Very nice project!  I made a few changes to adapt to my needs.  I offer this PR if you're interested.  If not, I understand.

Changes:
- Added code to allow specifying apps in code rather than through options, so multiple apps can be proxied in separate directories
- Added the ability to leave launch command empty and have SpaYarp not try to launch anything
- Added authorization policy name parameter so that apps proxied can be secured if desired.
- Added sample showing the multiple spa apps

These are nonbreaking; existing code works fine.

### CODE REVIEW

**Comment by berhir** [comment]
Sorry for the delay and thank you for the PR @JohnCampionJr! I would like to merge it, can you resolve the merge conflicts and update everything to the latest version? The new version supports now .NET 6 and .NET 7.

**Comment by JohnCampionJr** [comment]
OK, should be good; just tested it :)

**Comment by JohnCampionJr** [comment]
Any luck?  Would love to get this merged so I can quit privately hosting my version :)

**Comment by berhir** [comment]
Great, thanks! Can you add a brief description to the readme file? Then I will merge it

**Comment by JohnCampionJr** [comment]
Just added!

**Review by berhir — APPROVED** [review]
Thanks, I will publish a new version soon

**Pull request merged**
